services:
  - type: web
    name: raregh0st-site
    runtime: static
    buildCommand: pnpm install && pnpm run build && cp dist/index.html dist/200.html
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
